import {
  Home,
  Milk,
  TestTube,
  Box,
  Lamp,
  FileBarChart2,
  User,
  Recycle,
  Users,
  CalendarCheck,
  HeartPulse,
  WalletCards,
  BadgeCheck,
  Stethoscope,
  UserPlus,
  UserMinus,
  Clock,
  Calendar,
  Truck,
  Fuel,
  TriangleAlert,
  ClipboardList,
  PackageOpen,
  Medal,
  LifeBuoy,
  FlaskConical,
  CalendarRange,
  Clock1,
  Clock10Icon,
  Clock12,
  BarChart,
  FuelIcon,
  BarChart2Icon,
  Camera,
  Bell,
} from "lucide-react";
import ROUTES from "../routes/routes";

export const MENU_CONFIG = [
  //==============For Phase I ==============
  //common
  {
    label: "Dashboard",
    path: ROUTES.DASHBOARD,
    icon: Home,
    roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE", "HR", "TIMEKEEPER", "MICROBIOLOGIST", "PLANT_OPERATOR", "STORAGE_PACKAGING"],
    designations: ["CEO", "HR", "Plant Head", "Plant Operator", "Sales Manager", "Hub Manager", "Timekeeper", "Microbiologist", "Storage & Packaging Team", "Quality Assurance Team", "Accounts Staff", "HR Manager", "HR Executive"],
  },
  {
    label: "Attendance Logs",
    path: ROUTES.EMPLOYEE_ATTENDANCE,
    icon: CalendarCheck,
    roles: ["ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE", "TIMEKEEPER", "MICROBIOLOGIST", "PLANT_OPERATOR", "STORAGE_PACKAGING"],
    designations: ["Plant Operator", "Sales Manager", "Hub Manager", "Timekeeper", "Microbiologist", "Storage & Packaging Team", "Quality Assurance Team", "Accounts Staff"],
  },

  //ceo and plant-head
  {
    label: "User & Role Management",
    path: ROUTES.USER_ROLE_MANAGEMENT,
    icon: Users,
    roles: ["SUPER_ADMIN"],
    designations: ["CEO", "Plant Head"],
  },
  {
    label: "Rewards & Incentives",
    path: ROUTES.REWARDS_INCENTIVES,
    icon: Medal,
    roles: ["SUPER_ADMIN"],
    designations: ["CEO", "Plant Head"],
  },
  {
    label: "Compliance Reports",
    path: ROUTES.COMPLIANCE_REPORTS,
    icon: BadgeCheck,
    roles: ["SUPER_ADMIN"],
    designations: ["CEO", "Plant Head"],
  },
  {
    label: "Leaderboards",
    path: ROUTES.LEADERBOARDS,
    icon: Medal,
    roles: ["SUPER_ADMIN"],
    designations: ["CEO", "Plant Head"],
  },
  {
    label: "Growth Analytics",
    path: ROUTES.GROWTH_ANALYTICS,
    icon: BarChart2Icon,
    roles: ["SUPER_ADMIN"],
    designations: ["CEO", "Plant Head"],
  },
  {
    label: "Master Reports",
    path: ROUTES.MASTER_REPORTS,
    icon: FileBarChart2,
    roles: ["SUPER_ADMIN"],
    designations: ["CEO", "Plant Head"],
  },
  // {
  //   label: "Payment Oversight",
  //   path: ROUTES.PAYMENT_OVERSIGHT,
  //   icon: WalletCards,
  //   roles: ["Super Admin"],
  //   designations: ["CEO"],
  // },
  // {
  //   label: "System Settings",
  //   path: ROUTES.SYSTEM_SETTINGS,
  //   icon: Lamp,
  //   roles: ["Super Admin"],
  //   designations: ["CEO"],
  // },

  //hr
  {
    label: "Dashboard",
    path: ROUTES.DASHBOARD,
    icon: Home,
    roles: ["HR", "ADMIN", "SUPER_ADMIN"],
    designations: ["HR", "HR Manager", "HR Executive", "CEO"],
    group: "HR Management",
  },
   {
    label: "Attendance Logs",
    path: ROUTES.EMPLOYEE_ATTENDANCE,
    icon: CalendarCheck,
    roles: ["SUPER_ADMIN", "ADMIN", "HR"],
    designations: ["HR", "HR Manager", "HR Executive"],
  },
  {
    label: "Employee Attendance",
    path: ROUTES.ATTENDANCE_MANAGEMENT,
    icon: Clock,
    roles: ["SUPER_ADMIN", "ADMIN", "HR"],
    designations: ["HR", "HR Manager", "HR Executive"],
  },
  {
    label: "Employee Management",
    path: ROUTES.EMPLOYEE_MANAGEMENT,
    icon: Users,
    roles: ["SUPER_ADMIN", "ADMIN", "EXECUTIVE", "HR"],
    designations: ["HR", "Plant Head", "HR Manager", "HR Executive"],
    group: "HR Management",
  },
 {
    label: "Recruitment & Exit",
    path: ROUTES.STAFF_MOVEMENT,
    icon: Recycle,
    roles: ["Admin"],
    designations: ["HR", "HR Manager", "HR Executive"],
  },
  {
    label: "Health Records",
    path: ROUTES.HEALTH_LOG,
    icon: HeartPulse,
    roles: ["Admin", "Executive"],
    designations: ["HR", "HR Manager", "HR Executive", "Quality Assurance Team"],
  },
  {
    label: "Payroll",
    path: ROUTES.PAYROLL,
    icon: WalletCards,
    roles: ["Admin"],
    designations: ["HR", "HR Manager", "HR Executive"],
  },
  {
    label: "Certification",
    path: ROUTES.CERTIFICATION,
    icon: BadgeCheck,
    roles: ["Admin"],
    designations: ["HR", "HR Manager", "HR Executive"],
  },
  {
    label: "Medical Fitness",
    path: ROUTES.MEDICAL_FITNESS,
    icon: Stethoscope,
    roles: ["Admin"],
    designations: ["HR", "HR Manager", "HR Executive"],
  },
  // {
  //   label: "Reports",
  //   path: ROUTES.REPORT,
  //   icon: FileBarChart2,
  //   roles: ["HR", "ADMIN", "SUPER_ADMIN"],
  //   designations: ["HR", "HR Manager", "HR Executive", "CEO"],
  //   group: "HR Management",
  // },

  //timekeeper
  {
    label: "Create a Schedule",
    path: ROUTES.SCHEDULE_CREATOR,
    icon: CalendarRange,
    roles: ["SUPERVISOR", "EXECUTIVE", "SUPER_ADMIN", "MANAGER", "TIMEKEEPER"],
    designations: ["Timekeeper", "Sales Manager", "Quality Assurance Team", "Accounts Staff"],
    group: "Logistics",
  },
  {
    label: "Supply & Demand",
    path: ROUTES.PROMISES_REQUESTS,
    icon: Clock1,
    roles: ["SUPERVISOR", "EXECUTIVE", "TIMEKEEPER"],
    designations: ["Timekeeper"],
    group: "Logistics",
  },
  {
    label: "Trip Tracker",
    path: ROUTES.TRIP_TRACKER,
    icon: Truck,
    roles: ["SUPER_ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE", "TIMEKEEPER"],
    designations: ["Sales Manager", "Timekeeper"],
    group: "Logistics",
  },
  {
    label: "Fuel Log Review",
    path: ROUTES.FUEL_LOG_REVIEW,
    icon: Fuel,
    roles: ["SUPER_ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE", "TIMEKEEPER"],
    designations: ["Sales Manager", "Timekeeper"],
    group: "Logistics",
  },
  {
    label: "Issue Management",
    path: ROUTES.ISSUE_MANAGEMENT,
    icon: TriangleAlert,
    roles: ["SUPERVISOR", "EXECUTIVE", "SUPER_ADMIN", "MANAGER", "TIMEKEEPER"],
    designations: ["Timekeeper", "CEO", "Sales Manager", "QA Officer", "Accountant"],
  },
  {
    label: "Overall Logistics Status",
    path: ROUTES.OVERALL_STATUS,
    icon: BarChart,
    roles: ["SUPERVISOR", "EXECUTIVE", "TIMEKEEPER"],
    designations: ["Timekeeper"],
    group: "Logistics",
  },
  {
    label: "Performance",
    path: ROUTES.PERFORMANCE,
    icon: BarChart2Icon,
    roles: ["SUPER_ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE", "TIMEKEEPER"],
    designations: ["Timekeeper"],
    group: "Logistics",
  },

  //microbiologist
  {
    label: "Testings",
    path: ROUTES.MICRO_TESTINGS,
    icon: FlaskConical,
    roles: ["SUPERVISOR", "EXECUTIVE", "MICROBIOLOGIST"],
    designations: ["Microbiologist"],
    group: "Microbiologist",
  },
  {
    label: "Test Logs",
    path: ROUTES.MICRO_TEST_LOGS,
    icon: ClipboardList,
    roles: ["SUPERVISOR", "EXECUTIVE", "MICROBIOLOGIST"],
    designations: ["Microbiologist"],
    group: "Microbiologist",
  },
  {
    label: "Certifications",
    path: ROUTES.CERTIFICATION,
    icon: BadgeCheck,
    roles: ["SUPERVISOR", "EXECUTIVE", "MICROBIOLOGIST"],
    designations: ["Microbiologist"],
    group: "Microbiologist",
  },
  {
    label: "Support & Feedback",
    path: ROUTES.SUPPORTS,
    icon: LifeBuoy,
    roles: ["SUPERVISOR", "EXECUTIVE", "MICROBIOLOGIST"],
    designations: ["Microbiologist"],
  },

  //plant-operator
  {
    label: "Incoming Milk",
    path: ROUTES.INCOMING_MILK,
    icon: Milk,
    roles: ["SUPERVISOR", "EXECUTIVE", "PLANT_OPERATOR"],
    designations: ["SUPER_ADMIN", "ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE", "Plant Operator"],
    group: "Plant Operations",
  },
  {
    label: "Container Tracker",
    path: ROUTES.CONTAINER_TRACKER,
    icon: Box,
    roles: ["SUPERVISOR", "EXECUTIVE", "PLANT_OPERATOR"],
    designations: ["Plant Operator"],
    group: "Plant Operations",
  },
  {
    label: "Process Log",
    path: ROUTES.PROCESS_LOG,
    icon: Recycle,
    roles: ["SUPERVISOR", "EXECUTIVE", "PLANT_OPERATOR"],
    designations: ["Plant Operator"],
    group: "Plant Operations",
  },
  {
    label: "Lamp Maintenance",
    path: ROUTES.LAMP_MAINTENANCE,
    icon: Lamp,
    roles: ["SUPERVISOR", "EXECUTIVE", "PLANT_OPERATOR"],
    designations: ["Plant Operator"],
    group: "Plant Operations",
  },
  {
    label: "Area Photos",
    path: ROUTES.OPERATIONAL_PHOTOS,
    icon: Camera,
    roles: ["SUPERVISOR", "EXECUTIVE", "PLANT_OPERATOR"],
    designations: ["Plant Operator"],
    group: "Plant Operations",
  },

  //storage-packaging
  {
    label: "Dashboard",
    path: ROUTES.DASHBOARD,
    icon: Home,
    roles: ["SUPERVISOR", "EXECUTIVE", "STORAGE_PACKAGING", "SUPER_ADMIN"],
    designations: ["Storage & Packaging Team", "Storage Head", "Packaging Operator", "CEO"],
    group: "Storage & Packaging",
  },
  {
    label: "Storage and Packaging",
    path: ROUTES.STORAGE_PACKAGING,
    icon: PackageOpen,
    roles: ["SUPERVISOR", "EXECUTIVE", "STORAGE_PACKAGING"],
    designations: ["Storage & Packaging Team", "Storage Head", "Packaging Operator"],
    group: "Storage & Packaging",
  },
  {
    label: "Hub Requests",
    path: ROUTES.HUB_ALLOCATIONS,
    icon: Truck,
    roles: ["SUPERVISOR", "EXECUTIVE", "STORAGE_PACKAGING"],
    designations: ["Storage & Packaging Team", "Storage Head", "Packaging Operator"],
    group: "Storage & Packaging",
  },
  {
    label: "Inventory Management",
    path: ROUTES.INVENTORY_MANAGEMENT,
    icon: Box,
    roles: ["SUPERVISOR", "EXECUTIVE", "STORAGE_PACKAGING"],
    designations: ["Storage & Packaging Team", "Storage Head", "Packaging Operator"],
    group: "Storage & Packaging",
  },
  {
    label: "Reports",
    path: ROUTES.REPORT,
    icon: FileBarChart2,
    roles: ["SUPERVISOR", "EXECUTIVE", "STORAGE_PACKAGING"],
    designations: ["Storage & Packaging Team", "Storage Head", "Packaging Operator"],
    group: "Storage & Packaging",
  },
  //hub-manager
  {
    label: "Dashboard",
    path: ROUTES.DASHBOARD,
    icon: Home,
    roles: ["MANAGER", "SUPER_ADMIN", "HUB_MANAGER", "SALES_MANAGER"],
    designations: ["Hub Manager", "CEO"],
    group: "Hub Management",
  },
  {
    label: "Request Inventory",
    path: ROUTES.REQUEST_INVENTORY,
    icon: Box,
    roles: ["MANAGER", "SUPER_ADMIN", "HUB_MANAGER", "SALES_MANAGER"],
    designations: ["Hub Manager", "CEO"],
    group: "Hub Management",
  },
  {
    label: "Reports",
    path: ROUTES.REPORT,
    icon: FileBarChart2,
    roles: ["MANAGER", "SUPER_ADMIN", "HUB_MANAGER", "SALES_MANAGER"],
    designations: ["Hub Manager", "CEO"],
    group: "Hub Management",
  },
  //sales-manager
  // {
  //   label: "Dashboard",
  //   path: ROUTES.DASHBOARD,
  //   icon: Home,
  //   roles: ["MANAGER", "SUPER_ADMIN", "HUB_MANAGER", "SALES_MANAGER"],
  //   designations: ["Sales Manager", "CEO"],
  //   group: "Sales & Distribution",
  // },
  // {
  //   label: "Schedule Summary",
  //   path: ROUTES.SCHEDULE_SUMMARY,
  //   icon: ClipboardList,
  //   roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE"],
  //   designations: ["Sales Manager", "Quality Assurance Team", "Accounts Staff"],
  //   group: "Sales & Distribution",
  // },
  // {
  //   label: "Package Approval",
  //   path: ROUTES.PACKAGE_APPROVAL,
  //   icon: PackageOpen,
  //   roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE"],
  //   designations: ["Sales Manager", "Quality Assurance Team", "Accounts Staff"],
  //   group: "Sales & Distribution",
  // },
  // {
  //   label: "Reports",
  //   path: ROUTES.REPORT,
  //   icon: FileBarChart2,
  //   roles: ["MANAGER", "SUPER_ADMIN", "HUB_MANAGER", "SALES_MANAGER"],
  //   designations: ["Sales Manager", "CEO"],
  //   group: "Sales & Distribution",
  // },

  //quality-assurance

  //accounts-staff

  //common
  {
    label: "Reports",
    path: ROUTES.REPORT,
    icon: FileBarChart2,
    roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE"],
    designations: ["Sales Manager", "Storage & Packaging Team", "Storage Head", "Packaging Operator", "Quality Assurance Team", "Accounts Staff", "Hub Manager"],
    group: "General Reports",
  },
  {
    label: "Notifications",
    path: ROUTES.NOTIFICATIONS,
    icon: Bell,
    roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE", "HR", "TIMEKEEPER", "MICROBIOLOGIST", "PLANT_OPERATOR", "STORAGE_PACKAGING", "HUB_MANAGER", "SALES_MANAGER"],
    designations: ["CEO", "HR", "Plant Head", "Plant Operator", "Sales Manager", "Hub Manager", "Timekeeper", "Microbiologist", "Storage Head", "Packaging Operator", "QA Officer", "Accountant", "HR Manager", "HR Executive"],
  },
  {
    label: "Profile",
    path: ROUTES.PROFILE,
    icon: User,
    roles: ["SUPER_ADMIN", "ADMIN", "MANAGER", "SUPERVISOR", "EXECUTIVE", "HR", "TIMEKEEPER", "MICROBIOLOGIST", "PLANT_OPERATOR", "STORAGE_PACKAGING", "HUB_MANAGER", "SALES_MANAGER"],
    designations: ["CEO", "HR", "Plant Head", "Plant Operator", "Sales Manager", "Hub Manager", "Timekeeper", "Microbiologist", "Storage Head", "Packaging Operator", "QA Officer", "Accountant", "HR Manager", "HR Executive"],
  },
];
